openapi: 3.0.0
info:
  title: Aion
  description: iCal proxy and filter service
  version: 1.0.0
servers:
  - url: http://api.example.com/v1
paths:
  /calendars/id:
    post:
      summary: Create a calendar.
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                type: object
                example:
                  calendar:
                    summary: Example of a calendar
                    value:
                      url: webcal://www.meetup.com/ScienceOnTapORWA/events/ical/
                properties:
                  url:
                    type: string
    get:
      summary: Get a calendar by id.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                  id:
                    type: string
