service: aion

custom:
  calendarTableName: ${self:service}-${self:provider.stage}-calendar
  filterTableName: ${self:service}-${self:provider.stage}-filter
  dynamoEndpoint: https://dynamodb.us-west-2.amazonaws.com

provider:
  name: aws
  runtime: java8
  stage: ${opt:stage, "dev"}
  region: us-west-2
  memorySize: 512
  timeout: 20
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:Scan
        - dynamodb:Query
      Resource: "*"
  environment:
    DYNAMODB_ENDPOINT: ${self:custom.dynamoEndpoint}
    DYNAMODB_REGION: ${self:provider.region}
    CALENDAR_TABLE_NAME: ${self:custom.calendarTableName}
    FILTER_TABLE_NAME: ${self:custom.filterTableName}

package:
  artifact: build/libs/${self:service}.jar

functions:
  filter:
    handler: com.merricklabs.aion.handlers.FilterHandler
    events:
      - http:
          path: /filters
          method: post
      - http:
          path: /filters/{filterId}
          method: get
          request:
            parameters:
              paths:
                filterId: true

  calendar:
    handler: com.merricklabs.aion.handlers.CalendarHandler
    events:
      - http:
          path: /calendars
          method: post
      - http:
          path: /calendars/{calendarId}
          method: get
          request:
            parameters:
              paths:
                calendarId: true

  apply-filter:
    handler: com.merricklabs.aion.handlers.ApplyFilterHandler
    events:
      - http:
          path: /calendars/{calendarId}/apply/{filterId}
          method: get
          request:
            parameters:
              paths:
                calendarId: true
                filterId: true

resources:
  Resources:
    CalendarTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.calendarTableName}
    FilterTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.filterTableName}