version: 2
jobs:
  test:
    branches:
      only:
        - master
    docker:
      - image: circleci/openjdk:11.0.3-stretch
      - image: amazon/dynamodb-local
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      DYNAMODB_ENDPOINT: "http://localhost:8000"
      DYNAMODB_REGION: "us-east-1"
    steps:
      - run: ./gradlew test
  deploy:
    working_directory: ~/repo
      environment:
        JVM_OPTS: -Xmx3200m
        TERM: dumb
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y curl
      - run: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      - run: sudo apt-get install -y build-essential nodejs
      - run: sudo npm install -g serverless
      - checkout
      - deploy:
          requires:
            - hold
          name: Deploy to AWS
          command: ./gradlew deployPrd